// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp.Data;

namespace ServerApp.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("ServerApp.Models.AgirlikBirim", b =>
                {
                    b.Property<int>("BirimKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklamasi")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("BirimKodu");

                    b.ToTable("AgirlikBirim");
                });

            modelBuilder.Entity("ServerApp.Models.Material", b =>
                {
                    b.Property<string>("MalzemeKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("MalzemeAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("MalzemeKodu");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ServerApp.Models.MiktarBirim", b =>
                {
                    b.Property<int>("BirimKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklamasi")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("BirimKodu");

                    b.ToTable("MiktarBirim");
                });

            modelBuilder.Entity("ServerApp.Models.Order", b =>
                {
                    b.Property<long>("SistemSiparisNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Agirlik")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgirlikBirim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CikisAdresi")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MalzemeAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MalzemeKodu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<int>("MiktarBirim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifyOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriSiparisNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Not")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StateCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VarisAdresi")
                        .HasColumnType("TEXT");

                    b.HasKey("SistemSiparisNo");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ServerApp.Models.Statu", b =>
                {
                    b.Property<int>("StatuKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklamasi")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatuKodu");

                    b.ToTable("Statu");
                });

            modelBuilder.Entity("ServerApp.Models.StatuLog", b =>
                {
                    b.Property<long>("StatuLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DegisimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriSiparisNo")
                        .HasColumnType("TEXT");

                    b.Property<long>("SistemSiparisNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statu")
                        .HasColumnType("TEXT");

                    b.HasKey("StatuLogId");

                    b.ToTable("StatuLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
